name: Lint test
on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: '13.x'
    - run: npm install
    - run: $(npm bin)/web-ext lint --self-hosted